### ISSUE TITLE
Frederick_Assignment 4

### ISSUE THREAD

**Issue by JuliaFrederick** [epid8060fall2019/yangge-introduction#1]
You have a nicely organized Introducing Me page!
In it there is a section where you talk about software patterns, is this supposed to be patent? If not what is a software pattern, I don't know much about differences in software. 

Also could you tell us a little bit more about your switch from the active role in medicine you had to a PhD in epi? I think how those two things go together could be really interesting

-Julia Frederick

**Comment by ygechn** [comment]
Hi Julia,

Thank you for your comments. Yes, it should be patent which is a typo. I also add some words to explain my career.

Thank you.
