### ISSUE TITLE
Software patents?

### ISSUE THREAD

**Issue by ellenmonster** [epid8060fall2019/yangge-introduction#2]
Hi Yang,
I really enjoyed reading your introduction, and checking out the links you provided to your linked in and github pages! You mentioned two 'software patterns' that you have from your prior work. I'm not sure what a 'software pattern' is, but I was wondering if you meant 'software patent'?

Take care,
Ellen

**Comment by ygechn** [comment]
Hi Ellen,

Yes, it should be patent which is a typo. 

Thank you.
